baseURL = "/"
languageCode = "en-us"
title = "Blog | Escola Vitória-Régia"
theme = "tale"

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "backmain"
    name = "Voltar pro site"
    title = "Voltar pro site"
    url = "https://escolavitoriaregiacz.com.br/"
    weight = 0
